name: Make-Executables

on: workflow_dispatch

jobs:
  make-executable:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Make Executables
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn
      - run: yarn make
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: executables-${{ matrix.os }}
          path: out/make
